controller:
  allowSnippetAnnotations: true
  admissionWebhooks:
    enabled: true
  config:
    client-body-buffer-size: 32k
    client-header-buffer-size: 256k
    large-client-header-buffers: 4 256k
    log-format-escape-json: "true"
    log-format-upstream: '{"time":"$time_iso8601","proxy_protocol_addr":"$proxy_protocol_addr","remote_addr":"$remote_addr","x-forward-for":"$proxy_add_x_forwarded_for","request_id":"$req_id","request":"$request","remote_user":"$remote_user","bytes_sent":"$bytes_sent","body_bytes_sent":"$body_bytes_sent","request_time":"$request_time","status":"$status","vhost":"$host","request_proto":"$server_protocol","path":"$uri","request_query":"$args","request_length":"$request_length","method":"$request_method","http_referrer":"$http_referer","http_user_agent":"$http_user_agent","upstream":"$proxy_upstream_name","upstream_ip":"$upstream_addr","upstream_latency":"$upstream_response_time","upstream_status":"$upstream_status","tls":"$ssl_protocol/$ssl_cipher"}'
    proxy-buffer-size: 128k
  ingressClassResource:
    default: true
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
  publishService:
    enabled: true
  replicaCount: 2
  service:
    enabled: true
    externalTrafficPolicy: Cluster
    annotations:
      mk8s.mws.ru/load-balancer-external-ip-name: ingress-nginx
    nodePorts:
      http: 32079
      https: 32080
  watchIngressWithoutClass: true
defaultBackend:
  enabled: false
podSecurityPolicy:
  enabled: false
