replicaCount: 1

image:
  repository: registry.mwsapis.ru/mws-sdf/registry-cool-business-app/repository-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: app.webinar-26-04.nufl.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: app-tls-secret
      hosts:
        - app.webinar-26-04.nufl.ru

environment: dev

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
